name: Publish to npm

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests (if available)
        run: bun test || echo "No tests found, skipping..."
        continue-on-error: true

      - name: Setup Node.js for npm publish
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Publish to npm with retry
        run: |
          for i in 1 2 3; do
            echo "Attempt $i of 3"
            if npm publish --access public --provenance; then
              echo "Successfully published!"
              exit 0
            else
              echo "Attempt $i failed"
              if [ $i -lt 3 ]; then
                echo "Waiting 30 seconds before retry..."
                sleep 30
              fi
            fi
          done
          echo "All attempts failed"
          exit 1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
